version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Running tests and type checks"
      - npm run build --if-present
      - echo "Zipping build artifacts"
      - mkdir -p target
      - zip -r target/testartifacts.zip dist || echo "dist directory not found"

artifacts:
  files:
    - target/testartifacts.zip
